---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run at 06:10 on Sunday
    - cron: "10 6 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm
    steps:
      - name: Cache Podman and Buildah cache, storage, and configuration data across the build steps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/containers
            ~/.local/share/containers
            ~/.local/share/containers
            ~/.config/containers
            /var/lib/containers
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install the fish shell
        uses: fish-actions/install-fish@v1.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Use fuse
        run: |
          sudo apt-get install fuse-overlayfs
          mkdir -vp ~/.config/containers
          printf '[storage]\ndriver="overlay"\n\n[storage.options]\nmount_program="/usr/bin/fuse-overlayfs"\n' > ~/.config/containers/storage.conf

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image with Buildah
        run: buildah unshare ./build.fish --architecture ${{ matrix.arch }} --manifest screen-multiarch:latest

      - name: Export the image
        run: podman image save --format oci-archive -o screen-${{ matrix.arch }}.tar localhost/screen

      - uses: actions/upload-artifact@v2
        with:
          name: screen-${{ matrix.arch }}
          path: screen-${{ matrix.arch }}.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - arm
    steps:
      - name: Cache Podman and Buildah cache, storage, and configuration data across the build steps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/containers
            ~/.local/share/containers
            ~/.local/share/containers
            ~/.config/containers
            /var/lib/containers
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install the fish shell
        uses: fish-actions/install-fish@v1.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test the container
        run: ./test.fish --architecture ${{ matrix.arch }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Cache Podman and Buildah cache, storage, and configuration data across the build steps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/containers
            ~/.local/share/containers
            ~/.local/share/containers
            ~/.config/containers
            /var/lib/containers
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Push latest manifest and images to quay.io
        run: buildah manifest push --rm --all --creds jwillikers+publisher:${{ secrets.REGISTRY_PASSWORD }} screen-multiarch:latest docker://quay.io/jwillikers/screen
